### ISSUE TITLE
#Own task: Output of non-fitting regex (subject, group or sequence)

### ISSUE THREAD

**Issue by wulms** [wulms/BiDirect_BIDS_Converter#11]
Write output of non-fitting regex (that lead to an error).
This is a conservative function to check, that your file, subject and sequence naming is absolute.

**Comment by Vamillion** [comment]
You should print an example additionally so that the user can see what was covered by the given regex, and what was leaved out.

**Comment by wulms** [comment]
If subject-regex does not fit, only the non fitting subjects are shown.
Simply add the redundant appendices with `|appendice1|appendice2|reduntant1` to the `pattern_to_remove` in the `user/lut_study_info.csv`.
