### ISSUE TITLE
#Own_Task: Support and Testing for Siemens

### ISSUE THREAD

**Issue by Vamillion** [wulms/BiDirect_BIDS_Converter#3]
This issue is used for our own development processing.

This issue was made to integrate the standard functionality parameters relevant for Siemens
MRI devices. We will try to support them as well, because there usage in this field is of same size like phillips devices.

Task:
* Need to integrate the standard functionality parameter set
* Need to integrate the standard naming conventions 
* Need to update process flow

**Comment by wulms** [comment]
Tested on Siemens sequences. Take care - the sequence folders need to be directly in the subjects-id folder, no further nesting!
