### ISSUE TITLE
#Own task: Bash Script

### ISSUE THREAD

**Issue by wulms** [wulms/BiDirect_BIDS_Converter#8]
Write a wrapper script in bash. 
OS detection - dcm2niix download, unzip.
Prompt working directory.

**Comment by Vamillion** [comment]
That raises a question to me: Do we want to download the dicom2niix from bash or from R script? 🤔

**Comment by wulms** [comment]
I already implemented a function checking for OS, that downloads and unzips the tested version.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by wulms** [comment]
in Terminal: "
`Rscript --vanilla path_to_cloned_repository/start_BIDS_ConverteR.R /home/niklas/Test`
